rating/urls.py
# -*- coding: utf-8 -*-
#
# URL RATING CONFIG
#
from django.conf.urls.defaults import patterns, include, url
# Dajaxice Autodiscover
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

from views import *

urlpatterns = patterns('rating.views',
    #
    # Rating Views
    #
    url(r'^random/$', 'random_rating_view', name='random_rating'),

    url(r'^eval/semantic/(?P<ngram>[\w\ -_]+)/(?P<success_url>[\w\ -_]+)/$', 'eval_sem_diff_view', name='eval_sem_diff'),
    url(r'^eval/semantic/(?P<ngram>[\w\ -_]+)/$', 'eval_sem_diff_view', name='eval_sem_diff'),

    url(r'^eval/sensory/(?P<ngram>[\w\ -_]+)/(?P<success_url>[\w\ -_]+)/$', 'eval_sensory_dim_view', name='eval_sensory_dim'),
    url(r'^eval/sensory/(?P<ngram>[\w\ -_]+)/$', 'eval_sensory_dim_view', name='eval_sensory_dim'),

    url(r'^sort/(?P<ngram>[\w\ -_]+)/(?P<repeated>[True|False]+)/$', 'sort_ngram_view', name='sort_ngram'),
    url(r'^sort/(?P<ngram>[\w\ -_]+)/(?P<success_url>[\w\ -_]+)/$', 'sort_ngram_view', name='sort_ngram'),
    url(r'^sort/(?P<ngram>[\w\ -_]+)/$', 'sort_ngram_view', name='sort_ngram'),

    url(r'^(?P<ngram>[\w\ -_]+)/(?P<repeated>[True|False]+)/$', 'rate_assoc_view', name='rate_assoc'),
    url(r'^(?P<ngram>[\w\ -_]+)/(?P<success_url>[\w\ -_]+)/$', 'rate_assoc_view', name='rate_assoc'),
    url(r'^(?P<ngram>[\w\ -_]+)/$', 'rate_assoc_view', name='rate_assoc'),
    url(r'^$', 'rate_assoc_view', name='rate_assoc'),


    
    # DEPRECATED: NGram Setup Rating view for Admin
    #url(r'^ngramsetup/', 'ngram_setup_view', name='ngram_setup'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

xemanti/urls.py
# -*- coding: utf-8 -*-
#
# URL ROOT CONFIG
#
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from zinnia.models import Entry
from ngramengine.models import NGrams
from views import *

# Admin Autodiscover
from django.contrib import admin
admin.autodiscover()

# Dajaxice Autodiscover
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = patterns('xemanti.views',
    # General Views
    url(r'^$', StartView.as_view(), name='home'),
    url(r'^faq/', FAQView.as_view(), name='faq'),
    url(r'^impressum/',  ImpressumView.as_view(), name='impressum'),
    #
    # Registration Views
    #
    url(r'^accounts/login/', LoginView.as_view(), name='login_view'),
    url(r'^accounts/logout/', LogoutView.as_view(), name='logout_view'),
    url(r'^accounts/registration/',RegistrationView.as_view(), name='registration_view'),
    #
    # Application URL Includes
    #
    url(r'^engine/', include('ngramengine.urls')),
    url(r'^rating/', include('rating.urls')),
    url(r'^reporting/', include('reporting.urls')),
    
    #
    # Zinnia Weblog URLs
    #
    url(r'^blog/', include('zinnia.urls'), name='blog'),
    url(r'^comments/', include('django.contrib.comments.urls')),

    #
    # Admin URLs
    #
    # Mainenance Action via Celery
    #url(r'^maintenance/', 'XemantiCom.views.maintenance', name='maintenance'),
    
    # Admin Interface (Backend)
    url(r'^admin/', include(admin.site.urls)),
    # Admin Documentation 
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    # Dajaxice
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    
    # Robots.txt
    url(r'^robots.txt$', TemplateView.as_view(template_name='xemanti/robots.txt')),

)

# Add Staticfiles-Urlpattern to urlpattern
urlpatterns += staticfiles_urlpatterns()

# Sitemap.xml addition
blog_info_dict = {
    'queryset': Entry.published.all(),
    'date_field': 'start_publication',
}
ngram_info_dict = {
    'queryset': NGrams.objects.filter(active=True),
    'date_field': 'updated',
}
sitemaps = {
    'blog': GenericSitemap(blog_info_dict, priority=0.4, changefreq='daily'),
    'ngram': GenericSitemap(ngram_info_dict, priority=0.6, changefreq='hourly'),
}

urlpatterns += patterns('django.contrib.sitemaps.views',
    (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)

rating/models.py
from django.db import models

# Create your models here.

rating/forms.py
"""
PR-130627: Rating Forms
"""
from django import forms
from django.forms import ModelChoiceField
from django.utils.translation import ugettext as _
from ngramengine.models import NGrams, SemanticDifferential, SensoryDimensions

class RateAssociationForm(forms.Form):
    rating = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("State your immediate association..."),'autofocus':'autofocus','class':'unit-100'}), min_length=2, max_length=255)
    target = forms.CharField(widget=forms.HiddenInput())
    
    def __init__(self, *args, **kwargs):
        if "ngram" in kwargs: ngram = kwargs.pop('ngram')
        super(RateAssociationForm, self).__init__(*args, **kwargs)
        if "ngram" in locals(): 
            self.fields['rating'].label = ngram.token



class SortAssociationForm(forms.Form):
    #rating = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("State your immediate association..."),'autofocus':'autofocus','class':'unit-100'}), min_length=2, max_length=255)
    
    sorting = forms.CharField(widget=forms.HiddenInput())
    ngram = forms.CharField(widget=forms.HiddenInput())
    source = forms.CharField(widget=forms.HiddenInput())



class SemanticDifferentialForm(forms.ModelForm):
    class Meta:
         model = SemanticDifferential
         fields = ('evaluation', 'potency', 'activity')
         widgets = {
            'evaluation': forms.HiddenInput(),
            'potency': forms.HiddenInput(),
            'activity': forms.HiddenInput()
            }



class SensoryDimensionForm(forms.ModelForm):
    class Meta:
         model = SensoryDimensions
         fields = ('visual', 'auditory', 'cognition','kinesthetic', 'olfactory', 'gustatory')
         widgets = {
            'visual': forms.HiddenInput(),
            'auditory': forms.HiddenInput(),
            'cognition': forms.HiddenInput(),
            'kinesthetic': forms.HiddenInput(),
            'olfactory': forms.HiddenInput(),
            'gustatory': forms.HiddenInput()
            }

rating/views.py
# -*- coding: utf-8 -*-
# Generic Import Statement
from django.contrib import auth
from django import forms
from django.utils.translation import ugettext as _
from django.http import HttpResponse
from django.shortcuts import render_to_response, HttpResponseRedirect, render
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.conf import settings
from django.db.models import Q, F
from django.db.models import Count
from django.utils import simplejson
from django.contrib import messages
from django.views.generic import View, TemplateView, RedirectView, FormView
import itertools
from random import choice

# Custom Import Statement
from forms import RateAssociationForm, SortAssociationForm, SemanticDifferentialForm, SensoryDimensionForm
from ngramengine.tokenizer import Tokenizer
from ngramengine.models import *



def get_random_ngram(ordering="-rating_index",size=500):
    """
    Selects a random ngram from a ordered set of ngrams
    """
    excludes = PartOfSpeech.objects.filter(coocurrence_relevancy=False)
    ngram = choice( NGrams.objects.filter(active=True).exclude(partofspeech__in=excludes).order_by(ordering)[:size])
    return ngram



def rate_assoc_view(request, ngram=None, repeated=False, success_url=None):
    ngram_token = ngram
    # Form submitted:
    if request.method == 'POST':
        form = RateAssociationForm(request.POST)
        if 'skip' in request.POST:
            return HttpResponseRedirect(reverse('rate_assoc'))
        elif 'rate' in request.POST:
            if form.is_valid():
                # reload if the input exceeds 100 Chars
                if len( form.cleaned_data['rating'] ) >= 100:
                    return HttpResponseRedirect(reverse('rate_assoc'))
                # get source and target ngram
                source = NGrams.inject(token=form.cleaned_data['target'])
                target = NGrams.inject(token=form.cleaned_data['rating'])
                # Save Association
                Associations.inject(source, target)
                # Multiple Associations if multiple_tokens 
                multiple_tokens = Tokenizer.linear_token_list(form.cleaned_data['rating'])
                if len(multiple_tokens) > 1:
                    for t in multiple_tokens:
                        atomic_target = NGrams.inject(token=t)
                        Associations.inject(source, atomic_target)
                # Success Message
                messages.add_message(request, messages.SUCCESS, _('Thanks for rating!'), fail_silently=True)
                # Redirect
                if request.user.is_authenticated():
                    request.user.profile.income(1.11)
                    if repeated:
                        return HttpResponseRedirect(reverse('rate_assoc', args=(ngram_token, True)))
                    elif success_url:
                        return HttpResponseRedirect(reverse(success_url))
                    else:
                        return HttpResponseRedirect(reverse('rate_assoc'))
                else:
                    # Increment anonymous_rating session
                    if request.session.has_key('anonymous_rating'):
                        request.session['anonymous_rating']['state'] = int( request.session['anonymous_rating']['state'] ) + 1
                        request.session.modified = True
                    return HttpResponseRedirect( reverse( 'rate_assoc' ) )
            else:
                return HttpResponseRedirect(reverse('rate_assoc'))
    # Form not submitted:
    else:
        if ngram == None:
            ngram = get_random_ngram()
        else:
            ngram, created = NGrams.objects.get_or_create(token=ngram_token)
        # Get Suggestions for rating (json)
        rating_suggestions = simplejson.dumps( sorted( list(  itertools.chain(*ngram.get_all_outbound_tokens())  ) ) )
        # Unbound form
        form = RateAssociationForm(ngram=ngram)
        form.fields['target'] = forms.CharField(initial=ngram.token, widget=forms.widgets.HiddenInput())
        
        # Information for redirected Users: 
        if request.session.has_key('anonymous_rating'):
            messages.add_message(request, messages.INFO, _('Rate one Word and you will get redirected!'), fail_silently=True)
            
    # Render Template Home
    return render_to_response('rating/ngram_rating.html', {
        "form":form,
        "ngram":ngram,
        "rating_suggestions":rating_suggestions,
    }, context_instance=RequestContext(request))



#
# Sorting View for an NGram
#
def sort_ngram_view(request, ngram, repeated=False, success_url=None):
    # Get NGram to rate
    ngram, created = NGrams.objects.get_or_create(token=ngram)
    
    if request.method == 'POST':
        form = SortAssociationForm(request.POST)
        if form.is_valid():
            source = NGrams.objects.get(token=form.cleaned_data['source'])
             # Inject sorted target
            for type in form.cleaned_data['sorting'].split(","):
                if type == "not_related":
                    NotRelated.inject(ngram,source)
                elif type == "associated":
                    Associations.inject(ngram,source)
                elif type == "synonym":
                    Synonyms.inject(ngram,source)
                elif type == "antonym":
                    Antonyms.inject(ngram,source)
                elif type == "subcategory":
                    SubCategory.inject(ngram,source)
                elif type == "supercategory":
                    SuperCategory.inject(ngram,source)
                elif type == "example":
                    Examples.inject(ngram,source)
                elif type == "attribute":
                    Attributes.inject(ngram,source)
                else:
                    pass
            # Success Message
            messages.add_message(request, messages.SUCCESS, _('Thanks for rating!'), fail_silently=True)
            # Process Payment
            if request.user.is_authenticated():
                # Increment authenticated profile
                request.user.profile.income(2.22)
            else:
                # Increment anonymous_rating session
                if request.session.has_key('anonymous_rating'):
                    request.session['anonymous_rating']['state'] = int( request.session['anonymous_rating']['state'] ) + 1
                    request.session.modified = True
            if repeated:
                return HttpResponseRedirect(reverse('sort_ngram', kwargs={'ngram':ngram.token, 'repeated':True}))
            elif success_url:
                return HttpResponseRedirect(reverse(success_url))
            else:
                return HttpResponseRedirect(reverse('sort_ngram', kwargs={'ngram':ngram.token}))
    else:
        # Get Sorting List
        # TODO: Throws error if no outbound_tokens are present
        outbound_tokens = ngram.get_all_outbound_tokens()
        if len(outbound_tokens) == 0:
            # Redirect if no tokens
            return HttpResponseRedirect(reverse('rate_assoc', kwargs={'ngram':ngram.token,'success_url':success_url}))
        source = choice( list( set( itertools.chain( *outbound_tokens ) ) ) )
        # Setup Form
        form = SortAssociationForm(initial={'ngram': ngram.token,'source': source})
    
    # Render Template Home
    return render_to_response('rating/ngram_sorting.html', {
        "ngram":ngram,
        "source":source,
        "form":form,
        #"token_list":simplejson.dumps( token_list ),
    }, context_instance=RequestContext(request))



def eval_sem_diff_view(request, ngram, success_url=None):
    """
    View for adding attitude (via semantic differential) to an NGram
    """
    if request.method == 'POST':
        ngram = NGrams.objects.get(token=ngram)
        form = SemanticDifferentialForm(request.POST, instance=ngram)
        if form.is_valid():
            semdiff, created = SemanticDifferential.objects.get_or_create(ngram=ngram)
            semdiff.record(form.cleaned_data['evaluation'],form.cleaned_data['potency'],form.cleaned_data['activity'])
            # Success Message
            messages.add_message(request, messages.SUCCESS, _('Thanks for rating!'), fail_silently=True)
            if request.user.is_authenticated():
                # Increment authenticated profile
                request.user.profile.income(2.22)
            else:
                # Increment anonymous_rating session
                if request.session.has_key('anonymous_rating'):
                    request.session['anonymous_rating']['state'] = int( request.session['anonymous_rating']['state'] ) + 1
                    request.session.modified = True
            if success_url:
                return HttpResponseRedirect(reverse(success_url))
            else:
                return HttpResponseRedirect(reverse('inspect_query', kwargs={'ngram':ngram.token}))
    else:
        ngram = NGrams.objects.get(token=ngram)
        form = SemanticDifferentialForm(instance=ngram)
    # Render Template Home
    return render_to_response('rating/ngram_eval_sem_diff.html', {
        "ngram":ngram,
        "form":form,
    }, context_instance=RequestContext(request))



def eval_sensory_dim_view(request, ngram, success_url=None):
    """
    View for adding the sensory dimensions involved for an NGram
    """
    if request.method == 'POST':
        ngram = NGrams.objects.get(token=ngram)
        form = SensoryDimensionForm(request.POST, instance=ngram)
        if form.is_valid():
            sensdim, created = SensoryDimensions.objects.get_or_create(ngram=ngram)
            sensdim.record(form.cleaned_data['visual'],
                           form.cleaned_data['auditory'],
                           form.cleaned_data['cognition'],
                           form.cleaned_data['kinesthetic'],
                           form.cleaned_data['olfactory'],
                           form.cleaned_data['gustatory'],)

rating/templates/rating/ngram_eval_sem_diff.html
{% extends "xemanti/base.html" %}
{% load i18n %}
{% load reporting_tags %}

{% block metadata %}
	<title>Xemanti - Erstes Gefühl, bestes Gefühl</title>
	<meta content="Xemanti - Sprachtools für deine Texte. Welches Gefühl erzeugt {{ ngram }} bei dir?" name="description"></meta>
	<meta content="sprachtools,sprachtool,assoziation,text,texten,rhetorik,kommunikation,bedeutung,synonym,antonym,wörterbuch" name="keywords"></meta>
{% endblock metadata %}

{% block custom-js %}
<script type="text/javascript">
</script>
{% endblock custom-js %}


{% block main-content %}
	
	<div class="units-row-end">
		<div id="" class="unit-50">
			<div id="" class="units-row"><br>
			</div>
			<div id="" class="units-row">
				<center><a href="{% url 'inspect_query' ngram.token %}" title="{% trans "Inspect" %}">
					<h2>{{ ngram }}</h2>
				</a></center>
			</div>
			<div id="" class="units-row"><br>
			</div>
			<div id="" class="units-row">
                <p class="small blocktext">
                    {% blocktrans %}
                        What is your attitude towards <strong>{{ ngram }}</strong>?<br>
                        Please indicate on the right your attitude. Does {{ ngram }} appear
                        to you rather bad, weak and passive or rather good, strong and active? After you pressed
                        the buttons that best represent your attitude, please click on the button rate.
                    {% endblocktrans %}
				</p>
			</div>
		</div>
		
		<div id="" class="unit-50">
			<div id="" class="units-row">
				<span class="unit-100 btn-group" data-toggle="buttons" data-target="#id_evaluation">
					<button class="btn unit-40" value="-1.0">{% trans 'bad' %}</button>
					<button class="btn unit-20" value="0.0">{% trans 'neutral' %}</button>
					<button class="btn unit-40" value="1.0">{% trans 'good' %}</button>
				</span>
			</div>
			<div id="" class="units-row">
				<span class="unit-100 btn-group" data-toggle="buttons" data-target="#id_potency">
					<button class="btn unit-40" value="-1.0">{% trans 'weak' %}</button>
					<button class="btn unit-20" value="0.0">{% trans 'neutral' %}</button>
					<button class="btn unit-40" value="1.0">{% trans 'strong' %}</button>
				</span>
			</div>
			<div id="" class="units-row">
				<span class="unit-100 btn-group" data-toggle="buttons" data-target="#id_activity">
					<button class="btn unit-40" value="-1.0">{% trans 'passive' %}</button>
					<button class="btn unit-20" value="0.0">{% trans 'neutral' %}</button>
					<button class="btn unit-40" value="1.0">{% trans 'active' %}</button>
				</span>
			</div>
			<div id="" class="units-row">
				<div class="unit-centered unit-60">
					<form action="." method="post">
						{% csrf_token %}
						{{ form.as_p }}
						<input type="submit" value="{% trans "Rate" %}" class="btn width-100"/>
					</form>
				</div>
			</div>
		</div>
	</div>
	

{% endblock main-content %}

rating/templates/rating/ngram_rating.html
{% extends "xemanti/base.html" %}
{% load i18n %}
{% load ngramengine_tags %}

{% block metadata %}
	<title>Xemanti - Erster Gedanke, bester Gedanke</title>
	<meta content="Xemanti - Sprachtools für deine Texte. Dein erster Gedanke zählt. Mach Xemanti noch schlauer und sag was dir in den Sinn kommt." name="description"></meta>
	<meta content="sprachtools,sprachtool,assoziation,text,texten,rhetorik,kommunikation,bedeutung,synonym,antonym,wörterbuch" name="keywords"></meta>
{% endblock metadata %}

{% block custom-js %}
<script type="text/javascript">
	$(function() {
		$( "#id_rating" ).autocomplete({
			source: {{ rating_suggestions|safe }},
			messages: {
				noResults: '',
				results: function() {}
			}
		});
		$( "#target_ngram" ).effect( "slide", {}, 500 );
		$( "input#rate" ).click(function() {
			$( "div#money-badge" ).effect( "pulsate", {}, 500 );
		});
	});
</script>
{% endblock custom-js %}


{% block main-content %}

<div id="left-content" class="units-row unit-70">
	<div class="unit-centered unit-90">
		<form action="." method="POST" data-ajax="false">
		{% csrf_token %}
		{% for field in form.visible_fields %}
    		<div class="units-row">
				<div class="unit-33 ">
					<center>
						<a href="{% url 'inspect_query' ngram.token %}" title="{% trans "Inspect" %}">
							<h2 id="target_ngram">{{ field.label }}</h2>
						</a>
					</center>
					{% if user.is_superuser %}
						{% load admin_urls %}
						<br><a href="/admin/ngramengine/ngrams/{{ngram.id}}/" target="_blank" class="supersmall">
							{% trans "N-Gram Admin" %}
						</a>
					{% endif %}
				</div>
				<div class="unit-33 ui-widget">
					 {{ field }}
				</div>
				<div class="unit-33">
					<input class="width-50" id="rate" type="submit" name="rate" value={% trans "Rate" %} />
					{# <input class="width-50" type="submit" name="skip" value={% trans "Skip" %} /> #}
				</div>
				<div class="unit-100 supersmall">
					{{ field.help_text }}
				</div>
			</div>
		{% endfor %}
		{% for hidden in form.hidden_fields %} 
			{{ hidden }} 
		{% endfor %}
		
	</form>
	</div>
</div>

<div id="right-sidebar" class="unit-30">
	<div id="featured" class="units-row">
		<div id="featured-ngrams" class="unit-100">
			{% render_featured_ngrams %}
		</div>
	</div>
    <div id="featured" class="units-row">
		<div id="featured-ngrams" class="unit-100">
			{% if not request.user.is_authenticated %}
                {% include "xemanti/partials/_register_now_ad_partial.html"%}
            {% endif %}
		</div>
	</div>
</div>

{% endblock main-content %}

rating/templates/rating/ngram_setup.html
{% extends "xemanti/base.html" %}

{% block main-content %}
<div class="main-content">
	<form action="." method="POST" data-ajax="false">
		{% for field in form.visible_fields %}
    		{{ field.label }} {{ field }}<br>
		{% endfor %}
		<a href="http://de.wiktionary.org/wiki/{{form.instance.token}}" target="_blank">{{form.instance.token}} on Wiktionary</a>
		<br>
		<input type="submit" name="delete" value="Delete" />{% csrf_token %}
		<input type="submit" name="update" value="Submit" />
	</form>
</div>
{% endblock %}

rating/templates/rating/ngram_sorting.html
{% extends "xemanti/base.html" %}
{% load i18n %}
{% load reporting_tags %}

{% block metadata %}
	<title>Xemanti - Was sind das für Assoziationen?</title>
	<meta content="Xemanti - Sprachtools für deine Texte. Mach Xemanti noch schlauer und sortiere die Wörter in Kategorien." name="description"></meta>
	<meta content="sprachtools,sprachtool,assoziation,text,texten,rhetorik,kommunikation,bedeutung,synonym,antonym,wörterbuch" name="keywords"></meta>
{% endblock metadata %}

{% block custom-js %}
	<script type="text/javascript">
	
		$(function() {
		});
	
	</script>
{% endblock custom-js %}

{% block main-content %}
	
	<div class="units-row">
		<div id="" class="unit-60">
			<span class="btn-group" data-toggle="buttons" data-type="segmented" data-target="#id_sorting">
				<button class="btn btn-big width-100" value="not_related">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is not relevant for' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="associated">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is associated with' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="antonym">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is opposed to' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="synonym">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is synonymous to' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="supercategory">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is a super category of' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="subcategory">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is a sub category of' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="example">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is an example of' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
				<button class="btn btn-big unit-100" value="attribute">
					<div class="units-row-end">
						<div class="unit-30" ><b>{{ source }}</b></div>
						<div class="unit-40" >{% trans 'is an attribute of' %}</div>
						<div class="unit-30" ><b>{{ ngram }}</b></div>
					</div>
				</button>
			</span>
		</div>
		<div id="" class="unit-40" >
            <div id="" class="units-row">
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="{% trans "Rate" %}" class="btn width-100"/>
                </form>
			</div>
            <div id="" class="units-row">
                <p class="small blocktext">
                    {% blocktrans %}
                        Please sort <strong>{{ ngram }}</strong> by clicking the buttons where the containing statement
                        is true to you. If you are ready click on the 'Rate' button.<br>
                    {% endblocktrans %}
                    <a href='{{ ngram.get_absolute_url }}'>
                        {% blocktrans %} Click here if you want to go back inspecting {{ ngram }} {% endblocktrans %}
                    </a>
				</p>
			</div>
		</div>
	</div>

{% endblock main-content %}